### ISSUE TITLE
reference to NDJ is broken

### ISSUE THREAD

**Issue by okurz** [Fraunhofer-IIS/ogrp#1]
http://en.wikipedia.org/wiki/Line_Delimited_JSON was deleted because NDJ was actually not really referenced anywhere else. http://dataprotocols.org/ndjson/ should suffice as the new target but with a rename of name to NDJSON

**Comment by mstahl-iis** [comment]
It now forwards to https://en.wikipedia.org/wiki/JSON_Streaming#Line_delimited_JSON which is quite OK, I think.
