### ISSUE TITLE
More information about time_status and channel_state needed.

### ISSUE THREAD

**Issue by gfleisch** [Fraunhofer-IIS/ogrp#2]
Could please add more information about

`time_status = string, ; "FREE_RUNNING" / "COARSE" / "GPS_SYNCED" / ...`

and

`channel_state = string, ; "IDLE" / "SEARCHING" / "PULL_IN" / "LOCKED" / "SYNCED"`

What do these states mean?

**Comment by mstahl-iis** [comment]
**time_status:**
- FREE_RUNNING: No PVT, time is extrapolated with internal clock. After cold start, the time is completely wrong
- COARSE: At least one satellite is tracked and the NAV messages can be read. This means the time is accurate to about 30ms.
- GPS_SYNCED: A PVT can be computed. The time is typically accurate to about 100ns.

**channel_state:**
- IDLE: The channel is not used
- SEARCHING: The channel is used for acquisition
- PULL_IN: The channel already tracks a satellite, but is not yet stable (should not be used for PVT)
- LOCKED: The channel is locked to the satellite signal but did not yet receive navigation messages
- SYNCED: The channel is locked to the satellite signal and synchronized to the full time of transmission of the satellte. Now the channel can be used for PVT calculation.
